name: ECB-Zombies
author: [superpeanut911, geekguy44, MortuTBK]
description: CoD Zombies/PVP plugin for Endercraftbuild minecraft server! endercraftbuild.net!
website: http://ci.mortu.net/job/ECB-Zombies/
main: net.endercraftbuild.cod.CoDMain
version: 1.3.1
depend: [Vault, WorldGuard]

commands:
# player commands
  join:
    description: Joins a game.
    usage: |
      /<command> <name>
      Example: /<command> nacht - join the game on Nacht
      Example: /<command> nuketown - join the game on Nuketown
    permissions: cod.player.join
    permission-message: You do not have permission to run that command.
  leave:
    description: Leaves the game you are currently in.
    usage: /<command>
    permissions: cod.player.leave
    permission-message: You do not have permission to run that command.
  tpack:
    description: Texture
    usage: /<command>
  pl:
    description: Plugins
    usage: /<command>
  ?:
    description: Plugins
    usage: /<command>
  texture:
    description: Texture
    usage: /<command>
  setlevel:
    description: setlevel
    usage: setlevel (player) (level)
  ztoggleadvanced:
    description: toggles advanced
    usage: ztoggleadvanced (game)
  zminlevel:
    description: sets min level for game
    usage: zminlevel (game)
  cprivate:
    description: Toggles a games public/private state
    usage: /<command> (game)
  stats:
    description: Displays stats for the game you are in or a specified game.
    usage: |
      /<command> [name]
      Example: /<command> - shows the stats for the game you are currently in
      Example: /<command> nacht - shows the stats for the current nacht game
      Example: /<command> nuketown - shows the stats for the current nuketown game
    permissions: cod.player.stats
    permission-message: You do not have permission to run that command.

# generic admin commands
  csave:
    description: Saves the current games setup.
    usage: /<command> - saves the current games setup
    permissions: cod.admin.save
    permission-message: You do not have permission to run that command.
  zsendallhub:
    description: Hub
    usage: /<command>
    permissions: cod.admin.sendall
    permission-message: You do not have permission to run that
  creload:
    description: Reloads the plugin configuration.
    usage: /<command>
    permissions: cod.admin.reload
    permission-message: You do not have permission to run that command.
  cstart:
    description: Starts the specified game.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.start
    permission-message: You do not have permission to run that command.
  cstop:
    description: Stops the specified game.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.stop
    permission-message: You do not have permission to run that command.
  cremove:
    description: Removes the specified game.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.remove
    permission-message: You do not have permission to run that command.
  ctoggle:
    description: Enables/disabled the specified game.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.toggle
    permission-message: You do not have permission to run that command.

# zombies admin commands
  zcreate:
    description: Creates a new CoD Zombies game with the spawnpoint set to your current location.
    usage: |
      /<command> <name> <min players> <max players> <zombie multiplier> <max waves>
      Example: /<command> nacht 1 8 1 128
      Example: /<command> nuketown 2 16 2 128
    permissions: cod.admin.create
    permission-message: You do not have permission to run that command.
  tdmcreate:
    description: Creates a new CoD TDM game with the spawnpoint set to your current location.
    usage: |
      /<command> <name> <min players> <max players>
    permissions: cod.admin.create
    permission-message: You do not have permission to run that command.
  zedit:
    description: Edits an existing CoD Zombies game with the spawnpoint set to your current location.
    usage: |
      /<command> <name> <new name> <min players> <max players> <zombie multiplier> <max waves>
      Example: /<command> notch nacht 1 8 1 128
      Example: /<command> nooktown nuketown 2 16 2 128
    permissions: cod.admin.edit
    permission-message: You do not have permission to run that command.
  zmob:
    description: Sets a specific mob type to spawn on specified waves.
    usage: |
      /<command> <name> <wave> <type>
      Example: /<command> nacht 5 wolves - will spawn wolves on waves 5, 10, 15, etc.
      Example: /<command> nacht 6 spiders - will spawn spiders on waves 6, 12, 18, etc.
      Example: /<command> nacht 5 - will remove the specific mob setup
    permissions: cod.admin.mob
    permission-message: You do not have permission to run that command.
  zspawn:
    description: Puts you in CoD Zombies spawn edit mode, allowing you to add and remove spawners.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.spawn
    permission-message: You do not have permission to run that command.
  zbarrier:
    description: Puts you in CoD Zombies barrier edit mode, allowing you to add and remove barriers.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.barrier
    permission-message: You do not have permission to run that command.
  zdoor:
    description: Puts you in CoD Zombies door edit mode, allowing you to add and remove doors.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.door
    permission-message: You do not have permission to run that command.
  zlink:
    description: Puts you in CoD Zombies link add mode, allowing you to add door/spawner links.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.link
    permission-message: You do not have permission to run that command.
  zlinkclear:
    description: Clears CoD Zombies door/spawner links.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.linkclear
    permission-message: You do not have permission to run that command.
  zadvance:
    description: Forces the specified CoD Zombies game to advance to the next round.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.advance
    permission-message: You do not have permission to run that command.
  zlobby:
    description: Sets the lobby location for dead players in a CoD Zombies game.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.lobby
    permission-message: You do not have permission to run that command.
  setlobbysign:
    description: Sets the lobby sign loc
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.lobby
    permission-message: You do not have permission to run that command.

permissions:
  cod.*:
    description: Gives access to all commands/permissions.
    children:
      cod.player.*: true
      cod.admin.*: true
  cod.player.*:
    description: Gives access to all player commands/permissions.
    children:
      cod.player.join: true
      cod.player.join.*: true
      cod.player.leave: true
      cod.player.signs: true
      cod.player.stats: true
    default: true
  cod.player.join:
    description: Allows you to join a game.
  cod.player.join.*:
    description: Gives access to all games.
    default: true
  cod.player.leave:
    description: Allows you to leave a game.
  cod.player.stats:
    description: Allows you to view stats for a game.
  cod.player.signs:
    description: Allows you to use various game signs.
  cod.admin.*:
    description: Gives access to all CoD functionality.
    children:
      cod.admin.save: true
      cod.admin.reload: true
      cod.admin.start: true
      cod.admin.stop: true
      cod.admin.remove: true
      cod.admin.toggle: true
      cod.admin.zcreate: true
      cod.admin.zedit: true
      cod.admin.zlobby: true
      cod.admin.zmob: true
      cod.admin.zspawn: true
      cod.admin.zbarrier: true
      cod.admin.zdoor: true
      cod.admin.zlink: true
      cod.admin.zlinkclear: true
      cod.admin.zadvance: true
      cod.admin.signs: true
  cod.admin.save:
    description: Allows you to save the existing games setup.
  cod.admin.reload:
    description: Allows you to reload the plugin configuration.
  cod.admin.start:
    description: Allows you to start a specific game.
  cod.admin.stop:
    description: Allows you to stop a specific game.
  cod.admin.remove:
    description: Allows you to remove a specific game.
  cod.admin.toggle:
    description: Allows you to enable/disable a specific game.
  cod.admin.zcreate:
    description: Allows you to create a CoD Zombies game.
  cod.admin.zedit:
    description: Allows you to edit an existing CoD Zombies game.
  cod.admin.zlobby:
    description: Allows you to define a lobby for dead CoD Zombie players.
  cod.admin.zmob:
    description: Allows you to set specific mobs to spawn in CoD Zombies games.
  cod.admin.zspawn:
    description: Allows you to edit CoD Zombies game spawners.
  cod.admin.zbarrier:
    description: Allows you to edit CoD Zombies game barriers.
  cod.admin.zdoor:
    description: Allows you to edit CoD Zombies game doors.
  cod.admin.zlink:
    description: Allows you to add CoD Zombies game door/spawner links.
  cod.admin.zlinkclear:
    description: Allows you to clear CoD Zombies game door/spawner links.
  cod.admin.zadvance:
    description: Allows you to advance a CoD Zombies game to the next round.
  cod.admin.signs:
    description: Allows you to create/edit CoD signs.
  cod.donor.1:
    description: 1
  cod.donor.2:
      description: 2
  cod.donor.3:
      description: 3
  cod.donor:
        description: donor
  cod.admin.minlevel:
      description: min level
  cod.admin.setlevel:
      description: set a players level

