# Global configuration settings.


# Player kit setup.  In order for a player to get a kit when they spawn they
# must have a permission similar to 'cod.kits.zombies.normal'.  If a player
# has more than one kit permission, they will get all kits they have the proper
# permssion nodes for.
kits:
  zombies:
    normal:
      268:
        name: Knife
      290:
        name: Pistol
      337:
        name: Ammo
        quantity: 64
    donor:
      267:
        name: Combat Knife
      307:
        name: Body Armor
      292:
        name: AK-47
      337:
        name: Ammo
        quantity: 64


# Game save data will be appended after this point.
# DO NOTE EDIT unless you know exactly what you're doing.
