name: ECB-Zombies
author: [superpeanut911, geekguy44, MortuTBK]
description: CoD Zombies/PVP plugin for Endercraftbuild minecraft server! endercraftbuild.net!
website: http://ci.mortu.net/job/ECB-Zombies/
main: net.endercraftbuild.cod.CoDMain
version: 1.0
depend: [Vault, WorldGuard]

commands:
# player commands
  join:
    description: Joins a game.
    usage: |
      /<command> <name>
      Example: /<command> nacht - join the game on Nacht
      Example: /<command> nuketown - join the game on Nuketown
    permissions: cod.player.join
    permission-message: You do not have permission to run that command.
  leave:
    description: Leaves the game you are currently in.
    usage: /<command>
    permissions: cod.player.leave
    permission-message: You do not have permission to run that command.
    
# generic admin commands
  csave:
    description: Saves the current games setup.
    usage: /<command> - saves the current games setup
    permissions: cod.admin.save
    permission-message: You do not have permission to run that command.
  creload:
    description: Reloads the plugin configuration.
    usage: /<command>
    permissions: cod.admin.reload
    permission-message: You do not have permission to run that command.
  cstart:
    description: Starts the specified game.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.start
    permission-message: You do not have permission to run that command.
  cstop:
    description: Stops the specified game.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.stop
    permission-message: You do not have permission to run that command.

# zombies admin commands
  zcreate:
    description: Creates a new CoD Zombies game with the spawnpoint set to your current location.
    usage: |
      /<command> <name> <min players> <max players> <zombie multiplier> <max waves>
      Example: /<command> nacht 1 8 1 128
      Example: /<command> nuketown 2 16 2 128
    permissions: cod.admin.create
    permission-message: You do not have permission to run that command.
  zedit:
    description: Edits an existing CoD Zombies game with the spawnpoint set to your current location.
    usage: |
      /<command> <name> <new name> <min players> <max players> <zombie multiplier> <max waves>
      Example: /<command> notch nacht 1 8 1 128
      Example: /<command> nooktown nuketown 2 16 2 128
    permissions: cod.admin.edit
    permission-message: You do not have permission to run that command.
  zspawn:
    description: Puts you in CoD Zombies spawn edit mode, allowing you to add and remove spawners.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.spawn
    permission-message: You do not have permission to run that command.
  zbarrier:
    description: Puts you in CoD Zombies barrier edit mode, allowing you to add and remove barriers.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.barrier
    permission-message: You do not have permission to run that command.
  zdoor:
    description: Puts you in CoD Zombies door edit mode, allowing you to add and remove doors.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.door
    permission-message: You do not have permission to run that command.
  zlink:
    description: Puts you in CoD Zombies link add mode, allowing you to add door/spawner links.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.link
    permission-message: You do not have permission to run that command.
  zlinkclear:
    description: Clears CoD Zombies door/spawner links.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.linkclear
    permission-message: You do not have permission to run that command.

permissions:
  cod.*:
    description: Gives access to all commands/permissions.
    children:
      cod.player.*: true
      cod.admin.*: true
  cod.player.*:
    description: Gives access to all player commands/permissions.
    children:
      cod.player.join: true
      cod.player.leave: true
      cod.player.signs: true
    default: true
  cod.player.join:
    description: Allows you to join a game.
  cod.player.leave:
    description: Allows you to leave a game.
  cod.player.signs:
    description: Allows you to use various game signs.
  cod.admin.*:
    description: Gives access to all CoD functionality.
    children:
      cod.admin.save: true
      cod.admin.reload: true
      cod.admin.start: true
      cod.admin.stop: true
      cod.admin.zcreate: true
      cod.admin.zedit: true
      cod.admin.zspawn: true
      cod.admin.zbarrier: true
      cod.admin.zdoor: true
      cod.admin.zlink: true
      cod.admin.zlinkclear: true
      cod.admin.signs: true
  cod.admin.save:
    description: Allows you to save the existing games setup.
  cod.admin.reload:
    description: Allows you to reload the plugin configuration.
  cod.admin.start:
    description: Allows you to start a specific game.
  cod.admin.stop:
    description: Allows you to stop a specific game.
  cod.admin.zcreate:
    description: Allows you to create a CoD Zombies game.
  cod.admin.zedit:
    description: Allows you to edit an existing CoD Zombies game.
  cod.admin.zspawn:
    description: Allows you to edit CoD Zombies game spawners.
  cod.admin.zbarrier:
    description: Allows you to edit CoD Zombies game barriers.
  cod.admin.zdoor:
    description: Allows you to edit CoD Zombies game doors.
  cod.admin.zlink:
    description: Allows you to add CoD Zombies game door/spawner links.
  cod.admin.zlinkclear:
    description: Allows you to clear CoD Zombies game door/spawner links.
  cod.admin.signs:
    description: Allows you to create/edit CoD signs.
