name: ECB-Zombies
author: [superpeanut911, geekguy44, MortuTBK]
description: CoD Zombies/PVP plugin for Endercraftbuild minecraft server! endercraftbuild.net!
website: http://ci.mortu.net/job/ECB-Zombies/
main: net.endercraftbuild.cod.CoDMain
version: 1.0
depend: [Vault, WorldGuard]

commands:
# player commands
  join:
    description: Joins a game.
    usage: |
      /<command> <name>
      Example: /<command> nacht - join the game on Nacht
      Example: /<command> nuketown - join the game on Nuketown
    permissions: cod.player.join
    permission-message: You do not have permission to run that command.
  leave:
    description: Leaves the game you are currently in.
    usage: /<command>
    permissions: cod.player.leave
    permission-message: You do not have permission to run that command.
    
# generic admin commands
  save:
    description: Saves the current games setup.
    usage: /<command> - saves the current games setup
    permissions: cod.admin.save
    permission-message: You do not have permission to run that command.

# zombies admin commands
  zcreate:
    description: Creates a new CoD Zombies game with the spawnpoint set to your current location.
    usage: |
      /<command> <name> <min players> <max players> <zombie multiplier> <max waves>
      Example: /<command> nacht 1 8 1 128
      Example: /<command> nuketown 2 16 2 128
    permissions: cod.admin.create
    permission-message: You do not have permission to run that command.
  zedit:
    description: Edits an existing CoD Zombies game with the spawnpoint set to your current location.
    usage: |
      /<command> <name> <new name> <min players> <max players> <zombie multiplier> <max waves>
      Example: /<command> notch nacht 1 8 1 128
      Example: /<command> nooktown nuketown 2 16 2 128
    permissions: cod.admin.edit
    permission-message: You do not have permission to run that command.
  zspawn:
    description: Puts you in CoD Zombies spawn edit mode, allowing you to add and remove spawners.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.spawn
    permission-message: You do not have permission to run that command.
  zbarrier:
    description: Puts you in CoD Zombies barrier edit mode, allowing you to add and remove barriers.
    usage: |
      /<command> <name>
      Example: /<command> nacht
      Example: /<command> nuketown
    permissions: cod.admin.barrier
    permission-message: You do not have permission to run that command.

permissions:
  cod.*:
    description: Gives access to all commands.
    children:
      cod.player.*: true
      cod.admin.*: true
  cod.player.*:
    description: Gives access to all player commands.
    children:
      cod.player.join: true
      cod.player.leave: true
    default: true
  cod.player.join:
    description: Allows you to join a game.
  cod.player.leave:
    description: Allows you to leave a game.
  cod.admin.*:
    description: Gives access to all CoD functionality.
    children:
      cod.admin.save: true
      cod.admin.zcreate: true
      cod.admin.zedit: true
      cod.admin.zspawn: true
      cod.admin.zspawn: true
      cod.admin.signs: true
  cod.admin.save:
    description: Allows you to save the existing games setup.
  cod.admin.zcreate:
    description: Allows you to create a CoD Zombies game.
  cod.admin.zedit:
    description: Allows you to edit an existing CoD Zombies game.
  cod.admin.zspawn:
    description: Allows you to edit CoD Zombies game spawners.
  cod.admin.zbarrier:
    description: Allows you to edit CoD Zombies game barriers.
  cod.admin.signs:
    description: Allows you to create/edit CoD signs.
